version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Map Redis port
    volumes:
      - redis_data:/data  # Persist Redis data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend  # Assuming your backend is in a 'backend' directory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Map your backend port
    environment:
      - REDIS_HOST=redis  # Use the service name as host in your .env or code
      - REDIS_PORT=6379
      - NODE_ENV=development  # or production
    # If you're using .env files, you can mount them:
    volumes:
      - ./backend/.env:/app/.env
    depends_on:
      - redis  # Ensure Redis starts before backend

volumes:
  redis_data: